export default {
    state: {
        listProjects: [
            //  ----- 1 bedroom
            {
                id: 1,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 2,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 3,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Classic Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 4,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "Modern Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 5,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Minimal Bedroom table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 6,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 7,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Modern Medroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 8,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "Modern Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            //  ----- 2 bedroom
            {
                id: 9,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 10,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 11,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Classic Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 12,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Modern Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 13,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Minimal Bedroom table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 14,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 15,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Medroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 16,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            //  ----- 3 bedroom
            {
                id: 17,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 18,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 19,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Classic Minimal Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 20,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "Modern Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 21,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Minimal Bedroom table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 22,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 23,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Modern Medroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 24,
                idtitle: "bedroom",
                idflag: 2,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "Modern Bedroom",
                paragraph: "Decor / Artchitecture",
            },
            //  -----------------------------------
            //  ----- 1 bathroom
            {
                id: 25,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 26,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "Minimal Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 27,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Classic Minimal Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 28,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Modern Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 29,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Minimal Bathroom table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 30,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 31,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 32,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            //  ----- 2 bathroom
            {
                id: 33,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 34,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "Minimal Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 35,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Classic Minimal Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 36,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Modern Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 37,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Minimal Bathroom table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 38,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 39,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 40,
                idtitle: "bathroom",
                idflag: 1,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Bathroom",
                paragraph: "Decor / Artchitecture",
            },
            //  -----------------------------------
            //  ----- 1 kitchan
            {
                id: 41,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 42,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 43,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Classic Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 44,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 45,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Minimal Kitchan table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 46,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 47,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 48,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            //  ----- 2 kitchan
            {
                id: 49,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 50,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 51,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Classic Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 52,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 53,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Kitchan table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 54,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 55,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 56,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            //  ----- 3 kitchan
            {
                id: 57,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 58,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 59,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Classic Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 60,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 61,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Kitchan table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 62,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 63,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 64,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            //  ----- 4 kitchan
            {
                id: 65,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 66,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 67,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Classic Minimal Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 68,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 69,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Kitchan table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 70,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 71,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 72,
                idtitle: "kitchan",
                idflag: 3,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Kitchan",
                paragraph: "Decor / Artchitecture",
            },
            //  -----------------------------------
            //  ----- 1 livingarea
            {
                id: 73,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project5.png"),
                heading: "Minimal Livingarea",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 74,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project6.png"),
                heading: "Minimal Livingarea",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 75,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project7.png"),
                heading: "Classic Minimal Livingarea",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 76,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project8.png"),
                heading: "Modern Livingarea",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 77,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project3.png"),
                heading: "Minimal Livingarea table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 78,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project4.png"),
                heading: "System Table",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 79,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project1.png"),
                heading: "Modern Livingarea",
                paragraph: "Decor / Artchitecture",
            },
            {
                id: 80,
                idtitle: "livingarea",
                idflag: 4,
                flag: false,
                src: require("@/assets/img/project2.png"),
                heading: "Modern Livingarea",
                paragraph: "Decor / Artchitecture",
            },
        ],
    },
    getters: {
        getListProjects(state) {
            return state.listProjects;
        },
    },
};
